// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://h3ttwpei4zf2lmmrdrdgsaxfxq.appsync-api.us-west-1.amazonaws.com/graphql',
          region: 'us-west-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'iam users have apiKey'
        }
    }
};

export default config;
